networks:
  nrv.net:
    driver: bridge
services:

  api.nrv:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./nrv.env
    ports:
      - '44010:80'
    volumes:
      - ./app:/var/php
      - ./sql:/var/sql
    working_dir: /var/php
    networks:
      - nrv.net
    depends_on:
      - nrv.db
    command: php -S 0.0.0.0:80 -t /var/php/public
    
  nrv.db:
    image: 'postgres:latest'
    env_file: ./nrvdb.env
    ports:
      - '44012:5432'
    networks:
      - nrv.net
    volumes:
      - ./app/sql:/var/sql'

  adminer:
    image: adminer
    ports:
      - '44011:8080'
    networks:
      - nrv.net

